version: "3.3"
services:
  mysqldb:
    image: mysql:8.0
    logging:
        driver: none
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=foopassword
      - MYSQL_DATABASE=sea
      - MYSQL_USER=sea_usr
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql_init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  app:
    build:
        context: .
        dockerfile: Dockerfile
    links:
        - mysqldb:dbhost
    depends_on:
        - mysqldb
    restart: unless-stopped
    env_file: .env
volumes:
  db:
